regions:
- eu-north-1
- global

blocklist:
- 738582102279
- 046792967279
- 324427516708

resource-types:
  excludes:
  - EC2KeyPair
  - CloudWatchEventsRule
  - CloudWatchEventsTarget
  - KMSAlias
  - IAMSAMLProvider
  - ElasticacheCacheParameterGroup
  - Route53ResolverRule
  - SESReceiptFilter
  - FMSNotificationChannel
  - SESReceiptRuleSet
  - FMSPolicy
  - AWS::Timestream::Database
  - AWS::Timestream::ScheduledQuery
  - AWS::Timestream::Table
  - AWS::AppFlow::ConnectorProfile
  - AWS::AppFlow::Flow
  - AWS::AppRunner::Service
  - AthenaWorkGroup
  - MediaConvertQueue
  - QuickSightUser
  - QuickSightSubscription
  - XRaySamplingRule
  - XRayGroup
  - SageMakerApp
  - SageMakerDomain
  - SageMakerEndpointConfig
  - SageMakerEndpoint
  - SageMakerModel
  - SageMakerNotebookInstanceLifecycleConfig
  - SageMakerNotebookInstance
  - SageMakerNotebookInstanceState
  - SageMakerSpace
  - SageMakerUserProfiles
  - RoboMakerSimulationJob
  - RoboMakerSimulationApplication
  - RoboMakerRobotApplication
  - LightsailStaticIP
  - LightsailLoadBalancer
  - LightsailKeyPair
  - LightsailInstance
  - LightsailDomain
  - LightsailDisk
  - LexSlotType
  - LexModelBuildingServiceBotAlias
  - LexIntent
  - LexBot
  - CodeStarProject
  - CodeStarNotificationRule
  - CodeStarConnection
  - Cloud9Environment

accounts:
  "206332737656":
    filters:
      S3Bucket:
      - "s3://entigo-training-feedback"
      S3Object:
      - type: regex
        value: "s3://entigo-training-feedback/.*"
      Route53HostedZone:
      - "/hostedzone/Z0854848C083DV8BKUYJ (learn.entigo.io.)" #infralib.entigo.io.
      EC2TGW:
      - "tgw-092384f97967bfffe"
      IAMRole:
      - "AWSReservedSSO_AdministratorAccess_092014765180ea16"
      - "AWSServiceRoleForElastiCache"
      - "OrganizationAccountAccessRole"
      - "AWSServiceRoleForTrustedAdvisor"
      - "AWSServiceRoleForSSO"
      - "AWSServiceRoleForSupport"
      IAMRolePolicyAttachment:
      - "AWSReservedSSO_AdministratorAccess_092014765180ea16 -> AdministratorAccess"
      - "AWSServiceRoleForElastiCache -> ElastiCacheServiceRolePolicy"
      - "AWSServiceRoleForOrganizations -> AWSOrganizationsServiceTrustPolicy"
      - "AWSServiceRoleForSSO -> AWSSSOServiceRolePolicy"
      - "AWSServiceRoleForSupport -> AWSSupportServiceRolePolicy"
      - "AWSServiceRoleForTrustedAdvisor -> AWSTrustedAdvisorServiceRolePolicy"
      - "OrganizationAccountAccessRole -> AdministratorAccess"
